const GET_APPOINTMENT_SUCCESS = "GET_APPOINTMENT_SUCCESS";
const GET_APPOINTMENT_FAIL = "GET_APPOINTMENT_FAIL";
const GET_APPOINTMENT_LOADING = "GET_APPOINTMENT_LOADING";

export {
    GET_APPOINTMENT_SUCCESS,
    GET_APPOINTMENT_FAIL,
    GET_APPOINTMENT_LOADING
};
